### ISSUE TITLE
Auth Авторизація

### ISSUE THREAD

**Issue by ElizPery** [ElizPery/project-backend-DarkHorsesTeam#6]
middleware authenticate

Написати прошарок авторизації, що перевірятиме наявність токену та відповідність прав доступу

**Comment by ValeriyaHr** [comment]
додала src/middleware/authenticate.js
 
додано в src/routers
/water.js
import { authenticate } from '../middlewares/authenticate.js';
router.use(authenticate);

додано в src/routers
/auth.js
import { authenticate } from '../middlewares/authenticate.js';
І маршрути, які використовують authenticate для перевірки токена, що гарантує доступ до них лише авторизованим користувачам.
